from __future__ import annotations

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BASE_DIR / "data"
IMPORTS_DIR = DATA_DIR / "imports"
IMPORTERS_DIR = DATA_DIR / "importers"
CONTROLS_DIR = DATA_DIR / "controls"
OUTPUT_DIR = BASE_DIR / "output"
DATA_QUALITY_DIR = OUTPUT_DIR / "data_quality"
CHARTS_DIR = OUTPUT_DIR / "charts"
WEBSITE_DIR = OUTPUT_DIR / "website"
CONFIG_DIR = BASE_DIR / "config"

STEEL_CHAPTERS = ["72"]
VALID_TRANSPORT_MODES = {
    "10": "Sea",
    "20": "Rail",
    "30": "Road",
    "40": "Air",
    "50": "Mail",
    "60": "Roll-on/Roll-off",
    "70": "Fixed installation / Channel Tunnel",
    "80": "Inland waterway",
    "90": "Own propulsion",
}
IMPORT_RECORD_SLICES = {
    "PERREF": slice(0, 6),
    "TYPE": slice(6, 7),
    "MONTHAC": slice(7, 13),
    "COMCODE": slice(13, 21),
    "SITC": slice(21, 26),
    "COD_SEQ": slice(26, 29),
    "COD_ALPHA": slice(29, 31),
    "PORT_SEQ": slice(31, 34),
    "PORT_CODE": slice(34, 37),
    "COO_SEQ": slice(37, 40),
    "COO_ALPHA": slice(40, 42),
    "MODE_OF_TRANSPORT": slice(42, 44),
    "STAT_VALUE": slice(44, 56),
    "NET_MASS": slice(56, 68),
    "SUPP_UNIT": slice(68, 80),
    "SUPPRESSION": slice(80, 81),
    "FLOW": slice(81, 84),
    "REC_TYPE": slice(84, 85),
}
COUNTRY_NAMES = {
    "": "Unknown / not supplied",
    "AE": "United Arab Emirates",
    "AL": "Albania",
    "AM": "Armenia",
    "AT": "Austria",
    "AU": "Australia",
    "AZ": "Azerbaijan",
    "BA": "Bosnia and Herzegovina",
    "BE": "Belgium",
    "BG": "Bulgaria",
    "BR": "Brazil",
    "BY": "Belarus",
    "CA": "Canada",
    "CH": "Switzerland",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "CZ": "Czechia",
    "DE": "Germany",
    "DK": "Denmark",
    "DZ": "Algeria",
    "EE": "Estonia",
    "EG": "Egypt",
    "ES": "Spain",
    "FI": "Finland",
    "FK": "Falkland Islands",
    "FR": "France",
    "GB": "United Kingdom",
    "GE": "Georgia",
    "GR": "Greece",
    "HK": "Hong Kong",
    "HR": "Croatia",
    "HU": "Hungary",
    "ID": "Indonesia",
    "IE": "Ireland",
    "IL": "Israel",
    "IN": "India",
    "IS": "Iceland",
    "IT": "Italy",
    "JP": "Japan",
    "KE": "Kenya",
    "KG": "Kyrgyzstan",
    "KR": "South Korea",
    "KZ": "Kazakhstan",
    "LK": "Sri Lanka",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "LV": "Latvia",
    "MA": "Morocco",
    "MK": "North Macedonia",
    "MT": "Malta",
    "MX": "Mexico",
    "MY": "Malaysia",
    "NC": "New Caledonia",
    "NL": "Netherlands",
    "NO": "Norway",
    "OM": "Oman",
    "PH": "Philippines",
    "PK": "Pakistan",
    "PL": "Poland",
    "PT": "Portugal",
    "QV": "Unknown partner area",
    "RO": "Romania",
    "SA": "Saudi Arabia",
    "SE": "Sweden",
    "SG": "Singapore",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "SL": "Sierra Leone",
    "SM": "San Marino",
    "TH": "Thailand",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TW": "Taiwan",
    "UA": "Ukraine",
    "US": "United States",
    "VN": "Vietnam",
    "XS": "Serbia and Montenegro aggregate",
    "YY": "Confidential / unknown",
    "ZA": "South Africa",
    "ZW": "Zimbabwe",
}
